spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    # password: password
  jpa:
    hibernate:
      ddl-auto: update

server:
  servlet:
    context-path: /api

epidemicalert:
  token:
    expiryTime: 28800 # 8 hours

---

spring:
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5432/epidemicalert
  config:
    activate:
      on-profile: dev

JWT_SECRET: v1FEIolJXq2pKTtnzVtztbbL1RBf10Q6f56ImIZoj21nznP9rOdRN4dQ1iHrS494

---

spring:
  datasource:
    url: jdbc:postgresql://database-1.cw4vm04axn85.eu-west-1.rds.amazonaws.com/postgres
    username: postgres
    password: epidemicalerthardpassword
  config:
    activate:
      on-profile: prod

server:
  port: 443
  ssl:
    key-store:
      epidemicalert.tk.p12
    key-store-password:
      changeit
    keyStoreType:
      PKCS12

JWT_SECRET: Kj0ALWWB5PsZboojLMt24OXfSmjOQLUwC1EQFcnV9gA9E2KkDbxjT93SqZyUqr42
