create table t_zones
(
    zne_id            bigserial,
    zne_name          text,
    zne_level         text,
    zne_modification_date timestamp with time zone
);

insert into t_zones (zne_name, zne_level, zne_modification_date)
values ('powiat aleksandrowski', 'Y', now()),
       ('powiat augustowski', 'Y', now()),
       ('powiat bartoszycki', 'Y', now()),
       ('powiat bełchatowski', 'Y', now()),
       ('powiat będziński', 'Y', now()),
       ('powiat bialski', 'Y', now()),
       ('Biała Podlaska', 'Y', now()),
       ('powiat białobrzeski', 'Y', now()),
       ('powiat białogardzki', 'Y', now()),
       ('powiat białostocki', 'Y', now()),
       ('Białystok', 'Y', now()),
       ('powiat bielski', 'Y', now()),
       ('powiat bielski', 'Y', now()),
       ('Bielsko-Biała', 'Y', now()),
       ('powiat bieruńsko-lędziński', 'Y', now()),
       ('powiat bieszczadzki', 'Y', now()),
       ('powiat biłgorajski', 'Y', now()),
       ('powiat bocheński', 'Y', now()),
       ('powiat bolesławiecki', 'Y', now()),
       ('powiat braniewski', 'Y', now()),
       ('powiat brodnicki', 'Y', now()),
       ('powiat brzeski', 'Y', now()),
       ('powiat brzeski', 'Y', now()),
       ('powiat brzeziński', 'Y', now()),
       ('powiat brzozowski', 'Y', now()),
       ('powiat buski', 'Y', now()),
       ('powiat bydgoski', 'Y', now()),
       ('Bydgoszcz', 'Y', now()),
       ('Bytom', 'Y', now()),
       ('powiat bytowski', 'Y', now()),
       ('Chełm', 'Y', now()),
       ('powiat chełmiński', 'Y', now()),
       ('powiat chełmski', 'Y', now()),
       ('powiat chodzieski', 'Y', now()),
       ('powiat chojnicki', 'Y', now()),
       ('Chorzów', 'Y', now()),
       ('powiat choszczeński', 'Y', now()),
       ('powiat chrzanowski', 'Y', now()),
       ('powiat ciechanowski', 'Y', now()),
       ('powiat cieszyński', 'Y', now()),
       ('powiat czarnkowsko-trzcianecki', 'Y', now()),
       ('Częstochowa', 'Y', now()),
       ('powiat częstochowski', 'Y', now()),
       ('powiat człuchowski', 'Y', now()),
       ('Dąbrowa Górnicza', 'Y', now()),
       ('powiat dąbrowski', 'Y', now()),
       ('powiat dębicki', 'Y', now()),
       ('powiat drawski', 'Y', now()),
       ('powiat działdowski', 'Y', now()),
       ('powiat dzierżoniowski', 'Y', now()),
       ('Elbląg', 'Y', now()),
       ('powiat elbląski', 'Y', now()),
       ('powiat ełcki', 'Y', now()),
       ('powiat garwoliński', 'Y', now()),
       ('Gdańsk', 'Y', now()),
       ('powiat gdański', 'Y', now()),
       ('Gdynia', 'Y', now()),
       ('powiat giżycki', 'Y', now()),
       ('Gliwice', 'Y', now()),
       ('powiat gliwicki', 'Y', now()),
       ('powiat głogowski', 'Y', now()),
       ('powiat głubczycki', 'Y', now()),
       ('powiat gnieźnieński', 'Y', now()),
       ('powiat goleniowski', 'Y', now()),
       ('powiat golubsko-dobrzyński', 'Y', now()),
       ('powiat gołdapski', 'Y', now()),
       ('powiat gorlicki', 'Y', now()),
       ('powiat gorzowski', 'Y', now()),
       ('Gorzów Wielkopolski', 'Y', now()),
       ('powiat gostyniński', 'Y', now()),
       ('powiat gostyński', 'Y', now()),
       ('powiat górowski', 'Y', now()),
       ('powiat grajewski', 'Y', now()),
       ('powiat grodziski', 'Y', now()),
       ('powiat grodziski', 'Y', now()),
       ('powiat grójecki', 'Y', now()),
       ('Grudziądz', 'Y', now()),
       ('powiat grudziądzki', 'Y', now()),
       ('powiat gryficki', 'Y', now()),
       ('powiat gryfiński', 'Y', now()),
       ('powiat hajnowski', 'Y', now()),
       ('powiat hrubieszowski', 'Y', now()),
       ('powiat iławski', 'Y', now()),
       ('powiat inowrocławski', 'Y', now()),
       ('powiat janowski', 'Y', now()),
       ('powiat jarociński', 'Y', now()),
       ('powiat jarosławski', 'Y', now()),
       ('powiat jasielski', 'Y', now()),
       ('Jastrzębie-Zdrój', 'Y', now()),
       ('powiat jaworski', 'Y', now()),
       ('Jaworzno', 'Y', now()),
       ('Jelenia Góra', 'Y', now()),
       ('powiat jeleniogórski', 'Y', now()),
       ('powiat jędrzejowski', 'Y', now()),
       ('powiat kaliski', 'Y', now()),
       ('Kalisz', 'Y', now()),
       ('powiat kamiennogórski', 'Y', now()),
       ('powiat kamieński', 'Y', now()),
       ('powiat kartuski', 'Y', now()),
       ('Katowice', 'Y', now()),
       ('powiat kazimierski', 'Y', now()),
       ('powiat kędzierzyńsko-kozielski', 'Y', now()),
       ('powiat kępiński', 'Y', now()),
       ('powiat kętrzyński', 'Y', now()),
       ('Kielce', 'Y', now()),
       ('powiat kielecki', 'Y', now()),
       ('powiat kluczborski', 'Y', now()),
       ('powiat kłobucki', 'Y', now()),
       ('powiat kłodzki', 'Y', now()),
       ('powiat kolbuszowski', 'Y', now()),
       ('powiat kolneński', 'Y', now()),
       ('powiat kolski', 'Y', now()),
       ('powiat kołobrzeski', 'Y', now()),
       ('powiat konecki', 'Y', now()),
       ('Konin', 'Y', now()),
       ('powiat koniński', 'Y', now()),
       ('Koszalin', 'Y', now()),
       ('powiat koszaliński', 'Y', now()),
       ('powiat kościański', 'Y', now()),
       ('powiat kościerski', 'Y', now()),
       ('powiat kozienicki', 'Y', now()),
       ('powiat krakowski', 'Y', now()),
       ('Kraków', 'Y', now()),
       ('powiat krapkowicki', 'Y', now()),
       ('powiat krasnostawski', 'Y', now()),
       ('powiat kraśnicki', 'Y', now()),
       ('Krosno', 'Y', now()),
       ('powiat krośnieński', 'Y', now()),
       ('powiat krośnieński', 'Y', now()),
       ('powiat krotoszyński', 'Y', now()),
       ('powiat kutnowski', 'Y', now()),
       ('powiat kwidzyński', 'Y', now()),
       ('powiat legionowski', 'Y', now()),
       ('Legnica', 'Y', now()),
       ('powiat legnicki', 'Y', now()),
       ('powiat leski', 'Y', now()),
       ('powiat leszczyński', 'Y', now()),
       ('Leszno', 'Y', now()),
       ('powiat leżajski', 'Y', now()),
       ('powiat lęborski', 'Y', now()),
       ('powiat lidzbarski', 'Y', now()),
       ('powiat limanowski', 'Y', now()),
       ('powiat lipnowski', 'Y', now()),
       ('powiat lipski', 'Y', now()),
       ('powiat lubaczowski', 'Y', now()),
       ('powiat lubański', 'Y', now()),
       ('powiat lubartowski', 'Y', now()),
       ('powiat lubelski', 'Y', now()),
       ('powiat lubiński', 'Y', now()),
       ('Lublin', 'Y', now()),
       ('powiat lubliniecki', 'Y', now()),
       ('powiat lwówecki', 'Y', now()),
       ('powiat łańcucki', 'Y', now()),
       ('powiat łaski', 'Y', now()),
       ('powiat łęczycki', 'Y', now()),
       ('powiat łęczyński', 'Y', now()),
       ('powiat łobeski', 'Y', now()),
       ('Łomża', 'Y', now()),
       ('powiat łomżyński', 'Y', now()),
       ('powiat łosicki', 'Y', now()),
       ('powiat łowicki', 'Y', now()),
       ('powiat łódzki wschodni', 'Y', now()),
       ('Łódź', 'Y', now()),
       ('powiat łukowski', 'Y', now()),
       ('powiat makowski', 'Y', now()),
       ('powiat malborski', 'Y', now()),
       ('powiat miechowski', 'Y', now()),
       ('powiat mielecki', 'Y', now()),
       ('powiat międzychodzki', 'Y', now()),
       ('powiat międzyrzecki', 'Y', now()),
       ('powiat mikołowski', 'Y', now()),
       ('powiat milicki', 'Y', now()),
       ('powiat miński', 'Y', now()),
       ('powiat mławski', 'Y', now()),
       ('powiat mogileński', 'Y', now()),
       ('powiat moniecki', 'Y', now()),
       ('powiat mrągowski', 'Y', now()),
       ('Mysłowice', 'Y', now()),
       ('powiat myszkowski', 'Y', now()),
       ('powiat myślenicki', 'Y', now()),
       ('powiat myśliborski', 'Y', now()),
       ('powiat nakielski', 'Y', now()),
       ('powiat namysłowski', 'Y', now()),
       ('powiat nidzicki', 'Y', now()),
       ('powiat niżański', 'Y', now()),
       ('powiat nowodworski', 'Y', now()),
       ('powiat nowodworski', 'Y', now()),
       ('powiat nowomiejski', 'Y', now()),
       ('powiat nowosądecki', 'Y', now()),
       ('powiat nowosolski', 'Y', now()),
       ('powiat nowotarski', 'Y', now()),
       ('powiat nowotomyski', 'Y', now()),
       ('Nowy Sącz', 'Y', now()),
       ('powiat nyski', 'Y', now()),
       ('powiat obornicki', 'Y', now()),
       ('powiat olecki', 'Y', now()),
       ('powiat oleski', 'Y', now()),
       ('powiat oleśnicki', 'Y', now()),
       ('powiat olkuski', 'Y', now()),
       ('Olsztyn', 'Y', now()),
       ('powiat olsztyński', 'Y', now()),
       ('powiat oławski', 'Y', now()),
       ('powiat opatowski', 'Y', now()),
       ('powiat opoczyński', 'Y', now()),
       ('Opole', 'Y', now()),
       ('powiat opolski', 'Y', now()),
       ('powiat opolski', 'Y', now()),
       ('powiat ostrołęcki', 'Y', now()),
       ('Ostrołęka', 'Y', now()),
       ('powiat ostrowiecki', 'Y', now()),
       ('powiat ostrowski', 'Y', now()),
       ('powiat ostrowski', 'Y', now()),
       ('powiat ostródzki', 'Y', now()),
       ('powiat ostrzeszowski', 'Y', now()),
       ('powiat oświęcimski', 'Y', now()),
       ('powiat otwocki', 'Y', now()),
       ('powiat pabianicki', 'Y', now()),
       ('powiat pajęczański', 'Y', now()),
       ('powiat parczewski', 'Y', now()),
       ('powiat piaseczyński', 'Y', now()),
       ('Piekary Śląskie', 'Y', now()),
       ('powiat pilski', 'Y', now()),
       ('powiat pińczowski', 'Y', now()),
       ('powiat piotrkowski', 'Y', now()),
       ('Piotrków Trybunalski', 'Y', now()),
       ('powiat piski', 'Y', now()),
       ('powiat pleszewski', 'Y', now()),
       ('Płock', 'Y', now()),
       ('powiat płocki', 'Y', now()),
       ('powiat płoński', 'Y', now()),
       ('powiat poddębicki', 'Y', now()),
       ('powiat policki', 'Y', now()),
       ('powiat polkowicki', 'Y', now()),
       ('Poznań', 'Y', now()),
       ('powiat poznański', 'Y', now()),
       ('powiat proszowicki', 'Y', now()),
       ('powiat prudnicki', 'Y', now()),
       ('powiat pruszkowski', 'Y', now()),
       ('powiat przasnyski', 'Y', now()),
       ('powiat przemyski', 'Y', now()),
       ('Przemyśl', 'Y', now()),
       ('powiat przeworski', 'Y', now()),
       ('powiat przysuski', 'Y', now()),
       ('powiat pszczyński', 'Y', now()),
       ('powiat pucki', 'Y', now()),
       ('powiat puławski', 'Y', now()),
       ('powiat pułtuski', 'Y', now()),
       ('powiat pyrzycki', 'Y', now()),
       ('powiat raciborski', 'Y', now()),
       ('Radom', 'Y', now()),
       ('powiat radomski', 'Y', now()),
       ('powiat radomszczański', 'Y', now()),
       ('powiat radziejowski', 'Y', now()),
       ('powiat radzyński', 'Y', now()),
       ('powiat rawicki', 'Y', now()),
       ('powiat rawski', 'Y', now()),
       ('powiat ropczycko-sędziszowski', 'Y', now()),
       ('Ruda Śląska', 'Y', now()),
       ('powiat rybnicki', 'Y', now()),
       ('Rybnik', 'Y', now()),
       ('powiat rycki', 'Y', now()),
       ('powiat rypiński', 'Y', now()),
       ('powiat rzeszowski', 'Y', now()),
       ('Rzeszów', 'Y', now()),
       ('powiat sandomierski', 'Y', now()),
       ('powiat sanocki', 'Y', now()),
       ('powiat sejneński', 'Y', now()),
       ('powiat sępoleński', 'Y', now()),
       ('Siedlce', 'Y', now()),
       ('powiat siedlecki', 'Y', now()),
       ('Siemianowice Śląskie', 'Y', now()),
       ('powiat siemiatycki', 'Y', now()),
       ('powiat sieradzki', 'Y', now()),
       ('powiat sierpecki', 'Y', now()),
       ('powiat skarżyski', 'Y', now()),
       ('Skierniewice', 'Y', now()),
       ('powiat skierniewicki', 'Y', now()),
       ('powiat sławieński', 'Y', now()),
       ('powiat słubicki', 'Y', now()),
       ('powiat słupecki', 'Y', now()),
       ('Słupsk', 'Y', now()),
       ('powiat słupski', 'Y', now()),
       ('powiat sochaczewski', 'Y', now()),
       ('powiat sokołowski', 'Y', now()),
       ('powiat sokólski', 'Y', now()),
       ('Sopot', 'Y', now()),
       ('Sosnowiec', 'Y', now()),
       ('powiat stalowowolski', 'Y', now()),
       ('powiat starachowicki', 'Y', now()),
       ('powiat stargardzki', 'Y', now()),
       ('powiat starogardzki', 'Y', now()),
       ('powiat staszowski', 'Y', now()),
       ('powiat strzelecki', 'Y', now()),
       ('powiat strzelecko-drezdenecki', 'Y', now()),
       ('powiat strzeliński', 'Y', now()),
       ('powiat strzyżowski', 'Y', now()),
       ('powiat sulęciński', 'Y', now()),
       ('powiat suski', 'Y', now()),
       ('powiat suwalski', 'Y', now()),
       ('Suwałki', 'Y', now()),
       ('powiat szamotulski', 'Y', now()),
       ('Szczecin', 'Y', now()),
       ('powiat szczecinecki', 'Y', now()),
       ('powiat szczycieński', 'Y', now()),
       ('powiat sztumski', 'Y', now()),
       ('powiat szydłowiecki', 'Y', now()),
       ('powiat średzki', 'Y', now()),
       ('powiat średzki', 'Y', now()),
       ('powiat śremski', 'Y', now()),
       ('powiat świdnicki', 'Y', now()),
       ('powiat świdnicki', 'Y', now()),
       ('powiat świdwiński', 'Y', now()),
       ('powiat świebodziński', 'Y', now()),
       ('powiat świecki', 'Y', now()),
       ('Świętochłowice', 'Y', now()),
       ('Świnoujście', 'Y', now()),
       ('Tarnobrzeg', 'Y', now()),
       ('powiat tarnobrzeski', 'Y', now()),
       ('powiat tarnogórski', 'Y', now()),
       ('powiat tarnowski', 'Y', now()),
       ('Tarnów', 'Y', now()),
       ('powiat tatrzański', 'Y', now()),
       ('powiat tczewski', 'Y', now()),
       ('powiat tomaszowski', 'Y', now()),
       ('powiat tomaszowski', 'Y', now()),
       ('Toruń', 'Y', now()),
       ('powiat toruński', 'Y', now()),
       ('powiat trzebnicki', 'Y', now()),
       ('powiat tucholski', 'Y', now()),
       ('powiat turecki', 'Y', now()),
       ('Tychy', 'Y', now()),
       ('powiat wadowicki', 'Y', now()),
       ('Wałbrzych', 'Y', now()),
       ('powiat wałbrzyski', 'Y', now()),
       ('powiat wałecki', 'Y', now()),
       ('Warszawa', 'Y', now()),
       ('powiat warszawski zachodni', 'Y', now()),
       ('powiat wąbrzeski', 'Y', now()),
       ('powiat wągrowiecki', 'Y', now()),
       ('powiat wejherowski', 'Y', now()),
       ('powiat węgorzewski', 'Y', now()),
       ('powiat węgrowski', 'Y', now()),
       ('powiat wielicki', 'Y', now()),
       ('powiat wieluński', 'Y', now()),
       ('powiat wieruszowski', 'Y', now()),
       ('Włocławek', 'Y', now()),
       ('powiat włocławski', 'Y', now()),
       ('powiat włodawski', 'Y', now()),
       ('powiat włoszczowski', 'Y', now()),
       ('powiat wodzisławski', 'Y', now()),
       ('powiat wolsztyński', 'Y', now()),
       ('powiat wołomiński', 'Y', now()),
       ('powiat wołowski', 'Y', now()),
       ('Wrocław', 'Y', now()),
       ('powiat wrocławski', 'Y', now()),
       ('powiat wrzesiński', 'Y', now()),
       ('powiat wschowski', 'Y', now()),
       ('powiat wysokomazowiecki', 'Y', now()),
       ('powiat wyszkowski', 'Y', now()),
       ('Zabrze', 'Y', now()),
       ('powiat zambrowski', 'Y', now()),
       ('powiat zamojski', 'Y', now()),
       ('Zamość', 'Y', now()),
       ('powiat zawierciański', 'Y', now()),
       ('powiat ząbkowicki', 'Y', now()),
       ('powiat zduńskowolski', 'Y', now()),
       ('powiat zgierski', 'Y', now()),
       ('powiat zgorzelecki', 'Y', now()),
       ('Zielona Góra', 'Y', now()),
       ('powiat zielonogórski', 'Y', now()),
       ('powiat złotoryjski', 'Y', now()),
       ('powiat złotowski', 'Y', now()),
       ('powiat zwoleński', 'Y', now()),
       ('powiat żagański', 'Y', now()),
       ('powiat żarski', 'Y', now()),
       ('powiat żniński', 'Y', now()),
       ('Żory', 'Y', now()),
       ('powiat żuromiński', 'Y', now()),
       ('powiat żyrardowski', 'Y', now()),
       ('powiat żywiecki', 'Y', now());